### ISSUE TITLE
NetFX as a platform 

### ISSUE THREAD

**Issue by Scharps** [qian-o/SilkDemo#2]
Firstly, thank you for creating this repository!

I have managed to create a working copy in .NET. However, my project requires .NET Framework. I have tried creating this within a .NET Framework application and I get a PlatformNotSupportedException. Do you know why this is and perhaps what could be done to fix it?

**Comment by qian-o** [comment]
The issue you mentioned, I need you to take a few screenshots of the error messages.

**Comment by Scharps** [comment]
This is the thrown exception:

```
Unhandled Exception: System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'Project.ThreeD.ExampleScene' that matches the specified binding constraints threw an exception.' Line number '11' and line position '10'. ---> System.PlatformNotSupportedException: Couldn't find a suitable window platform. (none registered) https://dotnet.github.io/Silk.NET/docs/hlu/troubleshooting.html
   at Silk.NET.Windowing.Window.Create(WindowOptions options)
   at Project.ThreeD.RenderContext.GetOrCreateSharedOpenGlContext(Settings settings) in C:\Users\samuel.james\RiderProjects\[...]\Project.ThreeD\RenderContext.cs:line 74
   at Project.ThreeD.RenderContext..ctor(Settings settings) in C:\Users\samuel.james\RiderProjects\[...]\Project.ThreeD\RenderContext.cs:line 59
   at Project.ThreeD.ViewControl.OnStart() in C:\Users\samuel.james\RiderProjects\[...]\Project.ThreeD\ViewControl.cs:line 26
   at Project.ThreeD.ViewBase`1.Start() in C:\Users\samuel.james\RiderProjects\[...]\Project.ThreeD\ViewBase.cs:line 41
   at Project.ThreeD.ExampleScene..ctor() in C:\Users\samuel.james\RiderProjects\[...]\Project.ThreeD\ExampleScene.xaml.cs:line 26
```

The code is mostly the same to that in this repo. The only difference is that I've only implemented the OpenGL part and `GameBase` has be renamed to `ViewBase`.

**Comment by qian-o** [comment]
It looks like an exception was thrown when creating the window.
This piece of code is in the `GetOrCreateSharedOpenGLContext` method in `RenderContext`.
Its main purpose is to create a hidden `Window` and generate an OpenGL context of a specified version.
You need to check the supported OpenGL version on the platform and ensure that all dependencies are in place.

If the issue persists or if you're unsure how to proceed, feel free to share the code repository with me, and I can take a look.

**Comment by Scharps** [comment]
It was a problem with the project configuration. Thank you for your help
